import { AntdRegistry } from "@ant-design/nextjs-registry";
import "@ant-design/v5-patch-for-react-19";
import { App } from "antd";
import type { Metadata } from "next";
import { DictionaryProvider } from "../../../src/i18n/dictionaryContext";
import { i18n } from "../../../src/i18n/i18n.config";
import { enumLocale } from "../../../src/i18n/types";
import ThemeProvider from "../../../src/providers/theme/theme.provider";
import appViewModel from "./app.viewmodel";
import "./globals.css";

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export const metadata: Metadata = {
  title: "Template Symphony",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ lang: enumLocale }>;
}) {
  const resolvedParams = await params;
  const { lang } = resolvedParams;

  return (
    <html lang={lang}>
      <body suppressHydrationWarning={true}>
        <AntdRegistry>
          <ThemeProvider>
            <DictionaryProvider language={lang}>
              <App notification={{ placement: appViewModel.placementNoti }}>
                {children}
              </App>
            </DictionaryProvider>
          </ThemeProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
